### ISSUE TITLE
Need an option to remove all default styles 

### ISSUE THREAD

**Issue by RajNandigalla** [antoineaudrain/react-editorjs-renderer#5]
How can i remove all styles of the components being used by the Library

**Comment by antoineaudrain** [comment]
Hi, thank you for raising this issue. I just updated the documentation.
There is a special option `disable` in the custom style object, you can use it like so:

```
import EditorRendererProvider from 'react-editorjs-renderer';

...

const customStyle = {
  // disable style globally
  disable: true,
};

<EditorRendererProvider data={data} style={customStyle} />
```
